### ISSUE TITLE
SDL2 and OpenGX Port Advice Request

### ISSUE THREAD

**Issue by radicalten** [mardy/sdl-ogc-keyboard#1]
Hello Sir,

Thank you for your work on SDL2 and OpenGX! 

I am interested in porting Hydr8gon's DS emulator "NooDS" to the Wii (https://github.com/Hydr8gon/NooDS), and would like to ask for advice. 

Hydr8gon's project is written in C++, is Big-endian safe, uses SDL2 and OpenGL, and already has a port to the WiiU utilizing the WiiU's devkitpro SDL2 toolchain. With your recent developments in the ogc-sdl-2.28 and OpenGX libraries, I believe that a port to the Wii of this emulator is technically possible, and would be a very cool use of these libraries. 

Currently, I have my github actions virtual development environment set up to use the devkitpro/devkitppc:latest docker container, and to install ogc-sdl-2.28, opengx, and freeglut. Likewise for the makefile: LIBDIRS := $(PORTLIBS), and LIBS := -lopengx -lSDL2 -lfat -logc -lwiiuse -lwiikeyboard -lm -lbte -lGL -lGLU. 

With this dev environment, unfortunately I am unable to compile any .dol files using the example files from the OpenGX repository or the example in this sdl-ogc-keyboard repository. (I suspect I may need to change the makefile: lSDL2 -> lSDL, remove -lGL and -lGLU, and in the virtual dev enviroment remove freeglut installation entirely, but making these changes leads to a different set of compiler errors). 

If you could share some insight on how to properly set up the dev environment to use ocg-SDL2 (and if its even required to use OpenGX or freeglut together with SDL2, or if SDL2 can be used as a stand-alone library to port) that would be greatly appreciated. 

p.s.
Sorry if this is not the right place to ask for advice.

**Comment by mardy** [comment]
Hi!
  I suggest that you set sdl-ogc-keyboard aside for a while, because in order to build it you need one branch for SDL2 which has not been accepted upstream (yet?): https://github.com/devkitPro/SDL/pull/61

Also, the examples in the opengx repo are old, we need to clean them up a bit. If you are looking for some small projects to test opengx with, I recommend the files from this branch: https://github.com/mardy/freeglut/tree/with-tutorials/tutorials

Also, in order to use opengx with SDL2, this branch of SDL is needed: https://github.com/devkitPro/SDL/pull/74
Note that for the time being I've been more focused on integrating opengx with freeglut, so the SDL support is experimental. Please try it, and feel free to add a comment to that PR.

Good luck with NooDS, it sounds like it will be a fun project to port! :-D

**Comment by radicalten** [comment]
Thank you for this detailed explanation, I will try this out! 👍
